credentials:
  usernames:
    admin:
      email: mattgrapko@5law.ca
      failed_login_attempts: 0
      logged_in: False
      name: Matt
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - mattgrapko@gmail.com
