GEMINI_KEY = "AIzaSyDuBqec2-mhRF1qt9u7bqFAPr12RoGflu4"

PINECONE_KEY = "pcsk_3X4DDg_Jsf59AacQojDQxUGxMLCshLkTLmoCHW4PGByGCCQ3K76HjP8Yk5MbWSXvjQSnap"

SUPABASE_URL = "https://qpduiwhbvvggfrhkfifq.supabase.co"
SUPABASE_KEY = "sb_secret_fL25NlAf7U4NvCx8hb-s_g_iAXrg1S3"



[credentials.usernames.admin]
name = "Matt"
email = "mattgrapko@5law.ca"
logged_in = false

password = "Hellomum897$"

[cookie]
expiry_days = 30
key = "random_signature_key_change_this_later"
name = "8law_cookie"

[preauthorized]
emails = ["mattgrapko@gmail.com"]

