GEMINI_KEY = "AIzaSyDuBqec2-mhRF1qt9u7bqFAPr12RoGflu4"

PINECONE_KEY = "pcsk_3X4DDg_Jsf59AacQojDQxUGxMLCshLkTLmoCHW4PGByGCCQ3K76HjP8Yk5MbWSXvjQSnap"

PINECONE_API_KEY = "pcsk_5SZFEs_2rEhsZ9MiY1kw6jYDZHHYi9SqCa7jymFzxsTexfPxWQNn3YpGJ6bBV9XJPqKsgy"

PINECONE_INDEX = "https://8law-r087lln.svc.aped-4627-b74a.pinecone.io"

SUPABASE_URL = "https://qpduiwhbvvggfrhkfifq.supabase.co"
# .streamlit/secrets.toml

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwZHVpd2hidnZnZ2ZyaGtmaWZxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2ODI3Nzk4OCwiZXhwIjoyMDgzODUzOTg4fQ.rknxZxR-I41p-YioUjj9KydnZSLucZAeyupvFoLEVwQ" 

SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwZHVpd2hidnZnZ2ZyaGtmaWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNzc5ODgsImV4cCI6MjA4Mzg1Mzk4OH0.BLgqnwGJ1ebtOndj5_M3HxSDSKQrf-mYnqIt85qpjkY"

SUPABASE_EMAIL_REDIRECT_TO = "https://8lawaccountant-nlya5kponou5uq4rn5n7yj.streamlit.app"

AUTH_REDIRECT_URL = "https://8lawaccountant-nlya5kponou5uq4rn5n7yj.streamlit.app"

APP_URL = "https://8lawaccountant-nlya5kponou5uq4rn5n7yj.streamlit.app/"


OPENAI_API_KEY = "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"



DATABASE_URL = "postgresql://postgres:htMy5AVLW56GWoAF@db.qpduiwhbvvggfrhkfifq.supabase.co:5432/postgres?sslmode=require"


HCAPTCHA_SECRET_KEY = "ES_e8b8217a436a46ac8ae9b5c8e0f5f1b4"

HCAPTCHA_SITE_KEY = "86a09274-b2b0-4bee-95ce-2afe8f86f4be"

